MAP_FILE_DAT map_file_dat1[50] = {
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {2, 255},
        .dsp_pct = 33,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {2, 255},
        .dsp_pct = 33,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
};

