MAP_FILE_DAT map_file_dat0[50] = {
    {
        .stts = 0,
        .room = 18,
        .pos_x = 1743,
        .pos_y = 0,
        .pos_z = 1682,
        .get_msg = {42, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 18,
        .pos_x = 2393,
        .pos_y = -200,
        .pos_z = 1874,
        .get_msg = {38, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 18,
        .pos_x = 2393,
        .pos_y = -200,
        .pos_z = 1874,
        .get_msg = {255, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 41,
        .pos_x = 256,
        .pos_y = -500,
        .pos_z = 1700,
        .get_msg = {41, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 41,
        .pos_x = 256,
        .pos_y = -500,
        .pos_z = 1700,
        .get_msg = {255, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 18,
        .pos_x = 973,
        .pos_y = -175,
        .pos_z = 1365,
        .get_msg = {40, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {19, 20},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 40,
        .pos_x = 1264,
        .pos_y = -7,
        .pos_z = 2040,
        .get_msg = {23, 24},
        .dsp_pct = 32,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 27,
        .pos_x = -4731,
        .pos_y = 0,
        .pos_z = 7825,
        .get_msg = {6, 27},
        .dsp_pct = 32,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 6,
        .pos_x = 3148,
        .pos_y = 0,
        .pos_z = 452,
        .get_msg = {23, 27},
        .dsp_pct = 32,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 38,
        .pos_x = 1089,
        .pos_y = -280,
        .pos_z = 820,
        .get_msg = {28, 27},
        .dsp_pct = 32,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 30,
        .pos_x = 9226,
        .pos_y = 400,
        .pos_z = -7741,
        .get_msg = {48, 27},
        .dsp_pct = 32,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 33,
        .pos_x = 60,
        .pos_y = 0,
        .pos_z = 1363,
        .get_msg = {44, 27},
        .dsp_pct = 32,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 16,
        .pos_x = 5963,
        .pos_y = 0,
        .pos_z = 3549,
        .get_msg = {44, 43},
        .dsp_pct = 36,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 22,
        .pos_x = 2992,
        .pos_y = 0,
        .pos_z = 11149,
        .get_msg = {45, 43},
        .dsp_pct = 36,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 21,
        .pos_x = 3300,
        .pos_y = 0,
        .pos_z = 5800,
        .get_msg = {46, 43},
        .dsp_pct = 36,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 6,
        .pos_x = 3232,
        .pos_y = 400,
        .pos_z = 2353,
        .get_msg = {47, 43},
        .dsp_pct = 36,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 9,
        .pos_x = 176,
        .pos_y = -1100,
        .pos_z = 2701,
        .get_msg = {5, 30},
        .dsp_pct = 36,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 38,
        .pos_x = -1300,
        .pos_y = -400,
        .pos_z = 2706,
        .get_msg = {29, 30},
        .dsp_pct = 36,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 3,
        .pos_x = 310,
        .pos_y = -1400,
        .pos_z = 150,
        .get_msg = {31, 30},
        .dsp_pct = 36,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 38,
        .pos_x = -120,
        .pos_y = -600,
        .pos_z = 3300,
        .get_msg = {29, 30},
        .dsp_pct = 36,
        .msn_no = 2,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 40,
        .pos_x = 2600,
        .pos_y = -200,
        .pos_z = 2674,
        .get_msg = {25, 26},
        .dsp_pct = 21,
        .msn_no = 2,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 11,
        .pos_x = 1296,
        .pos_y = 0,
        .pos_z = 108,
        .get_msg = {35, 26},
        .dsp_pct = 21,
        .msn_no = 2,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 35,
        .pos_x = 366,
        .pos_y = -150,
        .pos_z = 1460,
        .get_msg = {32, 26},
        .dsp_pct = 21,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {36, 37},
        .dsp_pct = 22,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 3,
        .pos_x = 4949,
        .pos_y = 0,
        .pos_z = 1376,
        .get_msg = {34, 33},
        .dsp_pct = 33,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 3,
        .pos_x = 2741,
        .pos_y = -200,
        .pos_z = 1240,
        .get_msg = {10, 22},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 15,
        .pos_x = 264,
        .pos_y = 0,
        .pos_z = 1245,
        .get_msg = {2, 3},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 16,
        .pos_x = 5543,
        .pos_y = -400,
        .pos_z = 385,
        .get_msg = {2, 3},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 17,
        .pos_x = 2160,
        .pos_y = 0,
        .pos_z = 559,
        .get_msg = {2, 3},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 21,
        .pos_x = 400,
        .pos_y = -465,
        .pos_z = 6917,
        .get_msg = {21, 3},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 25,
        .pos_x = 5209,
        .pos_y = -2025,
        .pos_z = 8500,
        .get_msg = {16, 17},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 41,
        .pos_x = 1535,
        .pos_y = -180,
        .pos_z = 2388,
        .get_msg = {18, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 8,
        .pos_x = 6283,
        .pos_y = -1400,
        .pos_z = 2484,
        .get_msg = {2, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 1,
        .pos_x = 1684,
        .pos_y = -50,
        .pos_z = 287,
        .get_msg = {2, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 7,
        .pos_x = 1496,
        .pos_y = -330,
        .pos_z = 1950,
        .get_msg = {18, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 10,
        .pos_x = 2020,
        .pos_y = -280,
        .pos_z = 700,
        .get_msg = {18, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 17,
        .pos_x = 1400,
        .pos_y = 0,
        .pos_z = 4421,
        .get_msg = {2, 3},
        .dsp_pct = 33,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 23,
        .pos_x = 3005,
        .pos_y = 0,
        .pos_z = 5011,
        .get_msg = {2, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 1200,
        .pos_y = -400,
        .pos_z = 5188,
        .get_msg = {6, 7},
        .dsp_pct = 33,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 13,
        .pos_x = 4176,
        .pos_y = 0,
        .pos_z = 5106,
        .get_msg = {6, 7},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 1,
    },
};

