RELATION_DAT rel_dat[] = {
    {
        .up_p = &rel_dat[4],
        .down_p = &rel_dat[4],
        .left_p = &rel_dat[4],
        .right_p = &rel_dat[2],
        .parent_p = rel_prt,
        .plate_p = name_plate,
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 0,
        .attribute = 2,
        .msg_idx = 0,
        .tm2_id = 803,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[4],
        .down_p = &rel_dat[4],
        .left_p = &rel_dat[4],
        .right_p = &rel_dat[2],
        .parent_p = rel_prt,
        .plate_p = &name_plate[1],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 0,
        .attribute = 2,
        .msg_idx = 1,
        .tm2_id = 803,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = rel_dat,
        .down_p = rel_dat,
        .left_p = &rel_dat[4],
        .right_p = &rel_dat[4],
        .parent_p = rel_prt,
        .plate_p = &name_plate[2],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 2,
        .attribute = 2,
        .msg_idx = 2,
        .tm2_id = 804,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = rel_dat,
        .down_p = rel_dat,
        .left_p = &rel_dat[4],
        .right_p = &rel_dat[4],
        .parent_p = rel_prt,
        .plate_p = &name_plate[3],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 2,
        .attribute = 2,
        .msg_idx = 3,
        .tm2_id = 804,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = rel_dat,
        .down_p = rel_dat,
        .left_p = &rel_dat[2],
        .right_p = &rel_dat[2],
        .parent_p = rel_prt,
        .plate_p = &name_plate[4],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 4,
        .attribute = 2,
        .msg_idx = 4,
        .tm2_id = 805,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = rel_dat,
        .down_p = rel_dat,
        .left_p = &rel_dat[2],
        .right_p = &rel_dat[2],
        .parent_p = rel_prt,
        .plate_p = &name_plate[5],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 4,
        .attribute = 2,
        .msg_idx = 5,
        .tm2_id = 805,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[12],
        .down_p = &rel_dat[8],
        .left_p = &rel_dat[8],
        .right_p = &rel_dat[8],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[6],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 6,
        .attribute = 2,
        .msg_idx = 6,
        .tm2_id = 806,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[12],
        .down_p = &rel_dat[8],
        .left_p = &rel_dat[8],
        .right_p = &rel_dat[8],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[7],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 6,
        .attribute = 2,
        .msg_idx = 7,
        .tm2_id = 806,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[6],
        .down_p = &rel_dat[12],
        .left_p = &rel_dat[6],
        .right_p = &rel_dat[14],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[8],
        .ssd_p = &spr_dat[931],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[935],
        .dat_idx = 8,
        .attribute = 2,
        .msg_idx = 8,
        .tm2_id = 807,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[6],
        .down_p = &rel_dat[12],
        .left_p = &rel_dat[6],
        .right_p = &rel_dat[14],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[9],
        .ssd_p = &spr_dat[931],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[935],
        .dat_idx = 8,
        .attribute = 2,
        .msg_idx = 9,
        .tm2_id = 807,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[6],
        .down_p = &rel_dat[12],
        .left_p = &rel_dat[6],
        .right_p = &rel_dat[14],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[10],
        .ssd_p = &spr_dat[931],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[935],
        .dat_idx = 8,
        .attribute = 2,
        .msg_idx = 10,
        .tm2_id = 807,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[6],
        .down_p = &rel_dat[12],
        .left_p = &rel_dat[6],
        .right_p = &rel_dat[14],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[11],
        .ssd_p = &spr_dat[931],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[935],
        .dat_idx = 8,
        .attribute = 2,
        .msg_idx = 11,
        .tm2_id = 807,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[8],
        .down_p = &rel_dat[6],
        .left_p = &rel_dat[14],
        .right_p = &rel_dat[14],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[12],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 12,
        .attribute = 2,
        .msg_idx = 12,
        .tm2_id = 808,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[8],
        .down_p = &rel_dat[6],
        .left_p = &rel_dat[14],
        .right_p = &rel_dat[14],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[13],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 12,
        .attribute = 2,
        .msg_idx = 13,
        .tm2_id = 808,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[8],
        .down_p = &rel_dat[6],
        .left_p = &rel_dat[12],
        .right_p = &rel_dat[12],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[14],
        .ssd_p = &spr_dat[931],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[935],
        .dat_idx = 14,
        .attribute = 2,
        .msg_idx = 14,
        .tm2_id = 809,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[8],
        .down_p = &rel_dat[6],
        .left_p = &rel_dat[12],
        .right_p = &rel_dat[12],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[15],
        .ssd_p = &spr_dat[931],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[935],
        .dat_idx = 14,
        .attribute = 2,
        .msg_idx = 15,
        .tm2_id = 809,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[8],
        .down_p = &rel_dat[6],
        .left_p = &rel_dat[12],
        .right_p = &rel_dat[12],
        .parent_p = &rel_prt[1],
        .plate_p = &name_plate[16],
        .ssd_p = &spr_dat[931],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[935],
        .dat_idx = 14,
        .attribute = 2,
        .msg_idx = 16,
        .tm2_id = 809,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[19],
        .down_p = &rel_dat[19],
        .left_p = &rel_dat[19],
        .right_p = &rel_dat[21],
        .parent_p = &rel_prt[2],
        .plate_p = &name_plate[17],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 17,
        .attribute = 2,
        .msg_idx = 17,
        .tm2_id = 810,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[19],
        .down_p = &rel_dat[19],
        .left_p = &rel_dat[19],
        .right_p = &rel_dat[21],
        .parent_p = &rel_prt[2],
        .plate_p = &name_plate[18],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 17,
        .attribute = 2,
        .msg_idx = 18,
        .tm2_id = 810,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[17],
        .down_p = &rel_dat[17],
        .left_p = &rel_dat[21],
        .right_p = &rel_dat[21],
        .parent_p = &rel_prt[2],
        .plate_p = &name_plate[19],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 19,
        .attribute = 2,
        .msg_idx = 19,
        .tm2_id = 811,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[17],
        .down_p = &rel_dat[17],
        .left_p = &rel_dat[21],
        .right_p = &rel_dat[21],
        .parent_p = &rel_prt[2],
        .plate_p = &name_plate[20],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 19,
        .attribute = 2,
        .msg_idx = 20,
        .tm2_id = 811,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[17],
        .down_p = &rel_dat[17],
        .left_p = &rel_dat[19],
        .right_p = &rel_dat[19],
        .parent_p = &rel_prt[2],
        .plate_p = &name_plate[21],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 21,
        .attribute = 2,
        .msg_idx = 21,
        .tm2_id = 812,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[17],
        .down_p = &rel_dat[17],
        .left_p = &rel_dat[19],
        .right_p = &rel_dat[19],
        .parent_p = &rel_prt[2],
        .plate_p = &name_plate[22],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 21,
        .attribute = 2,
        .msg_idx = 22,
        .tm2_id = 812,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[17],
        .down_p = &rel_dat[17],
        .left_p = &rel_dat[19],
        .right_p = &rel_dat[19],
        .parent_p = &rel_prt[2],
        .plate_p = &name_plate[23],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 21,
        .attribute = 2,
        .msg_idx = 23,
        .tm2_id = 812,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[28],
        .down_p = &rel_dat[27],
        .left_p = NULL,
        .right_p = NULL,
        .parent_p = &rel_prt[3],
        .plate_p = &name_plate[24],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 24,
        .attribute = 2,
        .msg_idx = 24,
        .tm2_id = 813,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[28],
        .down_p = &rel_dat[27],
        .left_p = NULL,
        .right_p = NULL,
        .parent_p = &rel_prt[3],
        .plate_p = &name_plate[25],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 24,
        .attribute = 2,
        .msg_idx = 25,
        .tm2_id = 813,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[28],
        .down_p = &rel_dat[27],
        .left_p = NULL,
        .right_p = NULL,
        .parent_p = &rel_prt[3],
        .plate_p = &name_plate[26],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 24,
        .attribute = 2,
        .msg_idx = 26,
        .tm2_id = 813,
        .dsp_pos = 1,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[24],
        .down_p = &rel_dat[28],
        .left_p = NULL,
        .right_p = NULL,
        .parent_p = &rel_prt[3],
        .plate_p = &name_plate[27],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 27,
        .attribute = 2,
        .msg_idx = 27,
        .tm2_id = 814,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[27],
        .down_p = &rel_dat[24],
        .left_p = NULL,
        .right_p = NULL,
        .parent_p = &rel_prt[3],
        .plate_p = &name_plate[28],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 28,
        .attribute = 2,
        .msg_idx = 28,
        .tm2_id = 815,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = &rel_dat[27],
        .down_p = &rel_dat[24],
        .left_p = NULL,
        .right_p = NULL,
        .parent_p = &rel_prt[3],
        .plate_p = &name_plate[29],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 28,
        .attribute = 2,
        .msg_idx = 29,
        .tm2_id = 815,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = NULL,
        .down_p = NULL,
        .left_p = NULL,
        .right_p = NULL,
        .parent_p = &rel_prt[4],
        .plate_p = &name_plate[30],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 30,
        .attribute = 2,
        .msg_idx = 30,
        .tm2_id = -1,
        .dsp_pos = 0,
        .pad = 0,
    },
    {
        .up_p = NULL,
        .down_p = NULL,
        .left_p = NULL,
        .right_p = NULL,
        .parent_p = &rel_prt[4],
        .plate_p = &name_plate[31],
        .ssd_p = &spr_dat[929],
        .fnt_p = &spr_dat[937],
        .fla_p = &spr_dat[933],
        .dat_idx = 30,
        .attribute = 2,
        .msg_idx = 31,
        .tm2_id = -1,
        .dsp_pos = 0,
        .pad = 0,
    },
};

