static SUBTITLES_DAT subtitles_dat[] = {
    {
        .pos_x = 320,
        .pos_y = 354,
        .path = 1,
        .fr_rate = 1,
        .pri = 16,
        .attr = 0,
        .tbl = NULL,
        .list = subtitles_mov_list,
    },
    {
        .pos_x = 320,
        .pos_y = 342,
        .path = 0,
        .fr_rate = 2,
        .pri = 16,
        .attr = 0,
        .tbl = subtitles_tape_no,
        .list = subtitles_tape_list,
    },
    {
        .pos_x = 320,
        .pos_y = 354,
        .path = 0,
        .fr_rate = 2,
        .pri = 491520,
        .attr = 512,
        .tbl = NULL,
        .list = subtitles_mafuyu_list,
    },
    {
        .pos_x = 320,
        .pos_y = 354,
        .path = 0,
        .fr_rate = 2,
        .pri = 491520,
        .attr = 512,
        .tbl = subtitles_aghost_no,
        .list = subtitles_aghost_list,
    },
    {
        .pos_x = 320,
        .pos_y = 354,
        .path = 0,
        .fr_rate = 2,
        .pri = 491520,
        .attr = 512,
        .tbl = subtitles_ghost_d_no,
        .list = subtitles_ghost_d_list,
    },
    {
        .pos_x = 320,
        .pos_y = 354,
        .path = 0,
        .fr_rate = 2,
        .pri = 16,
        .attr = 0,
        .tbl = subtitles_priest_no,
        .list = subtitles_priest_list,
    },
};

