WANDER_SOUL_DAT wander_soul_dat[] = {
    {
        .destination_id = 0,
        .message_id = 0,
        .face_id = 622,
        .adpcm_id = 1937,
    },
    {
        .destination_id = 1,
        .message_id = 255,
        .face_id = 622,
        .adpcm_id = 65535,
    },
    {
        .destination_id = 2,
        .message_id = 1,
        .face_id = 622,
        .adpcm_id = 1935,
    },
    {
        .destination_id = 3,
        .message_id = 2,
        .face_id = 622,
        .adpcm_id = 1933,
    },
    {
        .destination_id = 4,
        .message_id = 255,
        .face_id = 622,
        .adpcm_id = 65535,
    },
    {
        .destination_id = 5,
        .message_id = 3,
        .face_id = 626,
        .adpcm_id = 1968,
    },
    {
        .destination_id = 6,
        .message_id = 4,
        .face_id = 624,
        .adpcm_id = 1917,
    },
    {
        .destination_id = 7,
        .message_id = 5,
        .face_id = 624,
        .adpcm_id = 1916,
    },
    {
        .destination_id = 8,
        .message_id = 6,
        .face_id = 623,
        .adpcm_id = 1931,
    },
    {
        .destination_id = 9,
        .message_id = 255,
        .face_id = 65535,
        .adpcm_id = 65535,
    },
    {
        .destination_id = 10,
        .message_id = 7,
        .face_id = 623,
        .adpcm_id = 1924,
    },
    {
        .destination_id = 11,
        .message_id = 8,
        .face_id = 624,
        .adpcm_id = 1919,
    },
    {
        .destination_id = 12,
        .message_id = 255,
        .face_id = 622,
        .adpcm_id = 65535,
    },
    {
        .destination_id = 13,
        .message_id = 9,
        .face_id = 623,
        .adpcm_id = 1927,
    },
    {
        .destination_id = 14,
        .message_id = 255,
        .face_id = 623,
        .adpcm_id = 65535,
    },
    {
        .destination_id = 15,
        .message_id = 255,
        .face_id = 623,
        .adpcm_id = 65535,
    },
    {
        .destination_id = 16,
        .message_id = 10,
        .face_id = 625,
        .adpcm_id = 1942,
    },
    {
        .destination_id = 17,
        .message_id = 255,
        .face_id = 65535,
        .adpcm_id = 65535,
    },
    {
        .destination_id = 18,
        .message_id = 11,
        .face_id = 625,
        .adpcm_id = 1947,
    },
    {
        .destination_id = 19,
        .message_id = 12,
        .face_id = 65535,
        .adpcm_id = 1952,
    },
    {
        .destination_id = 20,
        .message_id = 13,
        .face_id = 625,
        .adpcm_id = 1945,
    },
    {
        .destination_id = 21,
        .message_id = 14,
        .face_id = 626,
        .adpcm_id = 65535,
    },
    {
        .destination_id = 22,
        .message_id = 15,
        .face_id = 625,
        .adpcm_id = 65535,
    },
    {
        .destination_id = 23,
        .message_id = 16,
        .face_id = 626,
        .adpcm_id = 1972,
    },
    {
        .destination_id = 24,
        .message_id = 17,
        .face_id = 625,
        .adpcm_id = 1943,
    },
    {
        .destination_id = 25,
        .message_id = 255,
        .face_id = 65535,
        .adpcm_id = 65535,
    },
};

