#include "memory_addresses.h"

#include <stddef.h>

void* FontTextAddress = NULL;
void* ImgHdAddress = NULL;
void* IG_MSG_OBJ_ADDRESS = NULL;
void* EFFECT_ADDRESS = NULL;
//void* PBUF_ADDRESS = NULL;
void* SPRITE_ADDRESS = NULL;
void* PL_BGBG_PK2_ADDRESS = NULL;
void* PL_STTS_PK2_ADDRESS = NULL;
void* PL_PSVP_PK2_ADDRESS = NULL;
void* PL_SAVE_PK2_ADDRESS = NULL;
void* SV_PHT_PK2_ADDRESS = NULL;
void* M_SLCT_CMN_PK2_ADDRESS = NULL;
void* M_SLCT_STY_PK2_ADDRESS = NULL;
void* PL_OPTI_PK2_ADDRESS = NULL;
void* M_SLCT_BTL_CHR_PK2_ADDRESS = NULL;
void* M_SLCT_BTL_MSN_PK2_ADDRESS = NULL;
void* PL_SMAP_PK2_ADDRESS = NULL;
void* PL_PLAY_PK2_ADDRESS = NULL;
void* PL_PLDT_PK2_ADDRESS = NULL;
void* PL_MTOP_PK2_ADDRESS = NULL;
void* N_LOAD_PK2_ADDRESS = NULL;
void* HAND_PK2_ADDRESS = NULL;
void* PL_FNDR_PK2_ADDRESS = NULL;
void* PL_LIFE_PK2_ADDRESS = NULL;
void* ENEDMG_PK2_ADDRESS = NULL;
void* PHOTO001_PK2_ADDRESS = NULL;
void* TEST2D_PK2_ADDRESS = NULL;
void* TEST_ROOM_CHECK_ADDRESS = NULL;
void* MPEG_WORK_ADDRESS = NULL;
void* MISSION_TITLE_CARD_ADDRESS = NULL;
void* PL_ALBM_FSM_PK2_ADDRESS = NULL;
void* PLYR_FILE_ADDRESS = NULL;
void* PL_ALBM_SIDE_1_ADDRESS = NULL;
void* PL_PHOT_PK2_ADDRESS = NULL;
